#%RAML 1.0
title: Library Hours API
version: v1
baseUri: http://api.samplehost.com
protocols:
  - HTTPS
types:
  Hours:
    displayName: Hours
    type: object
    properties:
      locationId: string
      locationName: string
      open: datetime
      close: datetime
      message: string
/hours:
  get:
    description: Returns an array of library Hours.
    queryParameters:
      locationId:
        description: filter locations
      date:
        description: filter by date
    responses:
      200:
        body:
          application/json:
            example: |
              [{
                "locationId": "barker",
                "locationName" : "Barker Library",
                "open": "2018-05-30Z08:00:00",
                "closed": "2018-05-30Z10:00:00",
                "message": "Barker is closing early due to snow."
              },{
                "locationId": "dewey",
                "locationName" : "Dewey Library",
                "open": "2018-05-30Z08:00:00",
                "closed": "2018-05-30Z17:00:00"
              }]
      404:
        body:
          application/json:
            example: |
              {
                "message": "No matching location found."
              }
