#%RAML 1.0
title: Library Hours API
version: v1
baseUri: http://api.samplehost.com
protocols:
  - HTTPS
types:
  Hours:
    type: object
    properties:
      id: number
      location: string
      session:
        type: object
        properties:
          location: string
          open: datetime
          close: datetime
          message: string
/hours:
  get:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "location" : "Barker Library",
                "open": "2018-05-30Z00:00:00",
                "closed": "2018-05-30Z00:01:00",
                "message": "Barker is closing early due to snow."
              }
